name: generate-html-and-deploy-to-pages

on:
  push:
    branches: [ "gh-pages" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:3.1
        with:
          args: >-
            --standalone
            -f gfm
            -M title="Phlippie Bosman"
            -c resume.css
            -t html5
            -o index.html
            resume.md
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
